import Link from 'next/link';
import { ArrowUpRight, Check, Circle, Clock3, Minus, X } from 'lucide-react';
import type { RunDto, ReviewDto, TaskDetailDto } from '../../../src/control-plane/contracts.js';
import { duration, statusLabel } from '../../../src/control-plane/format.js';
import { LocalTime, Elapsed } from './live.js';
import { Empty, Section, Status } from './primitives.js';
const names: Record<string, string> = { codex: 'Codex', opencode: 'OpenCode', antigravity: 'Antigravity' };
function Field({ name, value, mono = false }: { name: string; value: string | null; mono?: boolean }) {
  return <div><dt>{name}</dt><dd className={mono ? 'mono' : ''}>{value ?? 'Not recorded'}</dd></div>;
}
function Attempt({ run }: { run: RunDto }) {
  const checkIcons = { pass: Check, fail: X, skipped: Minus, timeout: Clock3 };
  return <article className="attempt" id={`run-${run.id}`}><header className="attempt-header"><div><span className="eyebrow">ATTEMPT {String(run.attempt).padStart(2, '0')}</span><h3>{names[run.worker] ?? run.worker}</h3></div><div><Status status={run.status} /><Elapsed start={run.startedAt} end={run.finishedAt} /></div></header>
    <dl className="detail-fields"><Field name="Requested capability" value={run.capability} mono /><Field name="Selected worker / tier" value={run.selectedWorker ? `${run.selectedWorker}${run.tier ? ` / ${run.tier}` : ''}` : null} mono /><Field name="Model" value={run.model} mono /><Field name="Failure kind" value={run.failureKind} mono /><div><dt>Started</dt><dd><LocalTime value={run.startedAt} /></dd></div><div><dt>Finished</dt><dd>{run.finishedAt ? <LocalTime value={run.finishedAt} /> : 'In progress'}</dd></div><Field name="Parent run" value={run.parentRunId} mono /><Field name="Run ID" value={run.id} mono /></dl>
    {run.routeReason && <p className="route-reason">{run.routeReason}</p>}{run.fallbackReason && <p className="fallback-reason"><strong>Fallback</strong> {run.fallbackReason}</p>}{run.error && <p className="form-error">{run.error}</p>}
    {run.checks.length > 0 && <section className="verification"><h4>Deterministic verification</h4><ul>{run.checks.map((c, index) => { const Icon = checkIcons[c.status]; return <li key={`${c.name}-${index}`}><div className="check-row"><Icon size={15} className={`check-icon ${c.status}`} /><strong>{c.name}</strong><span className={`check-label ${c.status}`}>{c.status}</span><span className="mono">{duration(c.durationMs)}</span></div>{(c.status === 'fail' || c.status === 'timeout') && c.output && <pre className="failure-snippet">{c.output.slice(0, 350)}{c.output.length > 350 ? '…' : ''}</pre>}{c.output && <details><summary>{c.status === 'skipped' ? 'Why skipped' : 'Bounded output'}{c.outputTruncated ? ' · truncated' : ''}</summary><pre>{c.output}</pre></details>}</li>; })}</ul><p className="verification-note">Skipped checks are not evidence of passing tests. Verification timing is recorded per check; its timeline timestamp is the run finish.</p></section>}
    {run.workspace && <section className="workspace-inspection"><h4>Workspace</h4><dl className="workspace-fields"><Field name="Branch" value={run.workspace.branch} mono /><Field name="Worktree" value={run.workspace.path} mono /><Field name="Base" value={`${run.workspace.baseBranch} @ ${run.workspace.baseCommit.slice(0, 12)}`} mono /></dl>{run.git ? <><h5>Changed files <span className="muted">{run.git.changedFiles.length}</span></h5><ul className="changed-files">{run.git.changedFiles.map((file, i) => <li key={`${file}-${i}`} className="mono">{file}</li>)}</ul>{run.git.truncated && <p className="muted">Persisted workspace evidence is truncated.</p>}<details><summary>Git status & diff stat</summary><pre>{run.git.statusShort || 'No status changes recorded.'}</pre><pre>{run.git.diffStat || 'No tracked diff stat recorded.'}</pre></details></> : <p className="muted">No Git inspection result recorded yet.</p>}</section>}
    {run.message && <details className="worker-output"><summary>Worker message{run.messageTruncated ? ' · truncated' : ''}</summary><pre>{run.message}</pre></details>}
  </article>;
}
function Review({ review }: { review: ReviewDto }) {
  return <article className="review" id={`review-${review.id}`}><header className="review-header"><div><span className="eyebrow">INDEPENDENT REVIEW</span><h3>{names[review.reviewer] ?? review.reviewer}</h3><p className="mono">{review.provider} / {review.model ?? 'Model not recorded'}</p></div><div><span className={`review-verdict ${review.decision === 'approve' ? 'completed' : 'attention-text'}`}>{review.decision ? review.decision.replaceAll('_', ' ').toUpperCase() : statusLabel(review.status)}</span>{review.severity && <span className="muted">Severity · {review.severity}</span>}<LocalTime value={review.finishedAt ?? review.createdAt} /></div></header>
    {review.summary && <p className="review-summary">{review.summary}</p>}{review.error && <p className="form-error">{review.error}</p>}{review.findings.length ? <ol className="findings">{review.findings.map((f, i) => <li key={i}><div className="finding-meta"><span className="mono">{f.file ?? 'General finding'}{f.line ? `:${f.line}` : ''}</span><span>{f.category}</span></div><h4>{f.description}</h4><p>{f.reason}</p>{f.suggestedFix && <p className="finding-fix"><strong>Suggested fix</strong>{f.suggestedFix}</p>}</li>)}</ol> : review.decision && <p className="muted">No findings recorded.</p>}</article>;
}
export function TaskDetail({ detail }: { detail: TaskDetailDto }) {
  const { task, runs, reviews, timeline, decisions } = detail;
  return <><div className="task-introduction"><div><div className="eyebrow">OBJECTIVE</div><p className="prose">{task.objective}</p><div className="eyebrow criteria-title">ACCEPTANCE CRITERIA</div>{task.acceptanceCriteria.length ? <ul className="criteria">{task.acceptanceCriteria.map((c, i) => <li key={i}><Circle size={8} />{c}</li>)}</ul> : <p className="muted">No acceptance criteria recorded.</p>}</div><dl className="task-facts"><Field name="Repository" value={task.repository} mono /><Field name="Task ID" value={task.id} mono /><div><dt>Created / updated</dt><dd><LocalTime value={task.createdAt} /> / <LocalTime value={task.updatedAt} /></dd></div><Field name="Category / risk / difficulty" value={`${task.category} / ${task.risk} / ${task.difficulty}`} /><Field name="Task attempt budget" value={String(task.maxAttempts)} mono /></dl></div>
    {task.textTruncated && <p className="form-error">Some original task text is omitted by the display limits.</p>}
    {decisions.filter(e => e.status === 'open').map(e => <Link key={e.id} href={`/decisions/${e.id}`} className="task-decision-callout"><span className="dot waiting_human" /><div><strong>Your decision is needed</strong><p>{e.question}</p></div><ArrowUpRight size={18} /></Link>)}
    <div className="task-lifecycle"><section className="timeline-pane"><div className="section-heading"><h2>Lifecycle</h2><span className="mono">{timeline.length}</span></div><ol className="timeline">{timeline.map((e, i) => <li key={e.id}><span className={`timeline-node ${e.kind === 'created' || e.kind === 'completed' ? 'solid' : ''}`} /><span className="timeline-step mono">{String(i + 1).padStart(2, '0')} / <LocalTime value={e.at} timeOnly /></span>{e.ref ? <a href={`#${e.ref}`}><strong>{e.title}</strong></a> : <strong>{e.title}</strong>}{e.detail && <p>{e.detail}</p>}</li>)}</ol>{detail.historyTruncated && <p className="form-error">History is bounded. Some older records are omitted.</p>}</section><div className="evidence-pane"><Section title="Attempts & evidence" count={runs.length}>{runs.length ? runs.map(run => <Attempt key={run.id} run={run} />) : <Empty title="No attempt has started." detail="The task is waiting for execution." />}</Section>
      <Section title="Reviews" count={reviews.length}>{reviews.length ? reviews.map(review => <Review key={review.id} review={review} />) : <Empty title="No review recorded yet." />}</Section>
      {decisions.length > 0 && <Section title="Human decisions" count={decisions.length}>{decisions.map(e => <div key={e.id} className="task-escalation" id={`decision-${e.id}`}><div><span className="eyebrow">{e.reasonType} / {e.status}</span><LocalTime value={e.createdAt} /></div><Link href={`/decisions/${e.id}`}><strong>{e.question}</strong><ArrowUpRight size={14} /></Link><p>{e.summary}</p>{e.answer && <blockquote>{e.answer}</blockquote>}</div>)}</Section>}
      {task.context.length > 0 && <details className="task-context"><summary>Original task context</summary><ul>{task.context.map((v, i) => <li key={i}>{v}</li>)}</ul></details>}
    </div></div></>;
}
