import { expect, test } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, basename, resolve } from 'node:path';
import { execa } from 'execa';
import { Pool } from 'pg';
const databaseUrl=process.env.DATABASE_URL;
test('real DB projects, memory inspection/search and safe project/repository delegation',async ({page,request}) => {
  if(!databaseUrl)throw new Error('Set DATABASE_URL for isolated real DB browser QA.');
  const pool=new Pool({connectionString:databaseUrl}),directory=await mkdtemp(join(tmpdir(),'memory-browser-'));
  const projectName=`Browser memory QA ${randomUUID()}`,errors:string[]=[];let projectId:string|undefined,registryId:string|undefined;
  const before=(await pool.query('select count(*)::int as count from tasks')).rows[0].count;
  page.on('pageerror',e => errors.push(e.message));
  try {
    await execa('git',['init','-b','main',directory]);const path=await realpath(directory),repositoryName=basename(path);
    await page.goto('/repositories');await expect(page.getByRole('heading',{name:'Repositories',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'+ Add repository',exact:true}).click();await page.getByLabel('Repository path').fill(path);await page.getByRole('button',{name:'Add repository',exact:true}).click();await expect(page.getByRole('status').filter({hasText:`Registered ${repositoryName}`})).toBeVisible();
    registryId=(await pool.query('select id from repositories where path=$1',[path])).rows[0].id;
    await expect(page.getByRole('link',{name:repositoryName,exact:true}).first()).toBeVisible();
    await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Projects',exact:true}).click();await expect(page.getByRole('heading',{name:'Projects',exact:true})).toBeVisible();await page.getByLabel('Name',{exact:true}).fill(projectName);await page.getByLabel('Description',{exact:true}).fill('Portfolio architecture QA fixture');
    await page.getByRole('checkbox',{name:repositoryName,exact:true}).check();await page.getByRole('combobox',{name:'Primary repository',exact:true}).selectOption({label:repositoryName});await page.getByLabel('Goals',{exact:true}).fill('Build market data');await page.getByLabel('Constraints',{exact:true}).fill('Keep data local');await page.getByLabel('Instructions',{exact:true}).fill('Use server-only services');await page.getByLabel('Current milestone',{exact:true}).fill('Portfolio Lab');
    await page.getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByRole('heading',{name:projectName,exact:true})).toBeVisible();projectId=new URL(page.url()).pathname.split('/')[2]!;
    await expect(page.getByRole('link',{name:repositoryName,exact:true})).toBeVisible();await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Projects',exact:true}).click();await expect(page.getByRole('row').filter({hasText:projectName})).toContainText('Portfolio Lab');await page.evaluate(() => window.scrollTo(0,0));await page.screenshot({path:resolve('docs/project-memory-v1/projects-desktop.png'),fullPage:true});
    await page.getByRole('link',{name:projectName,exact:true}).click();await page.getByText('Edit project & repository bindings',{exact:true}).click();await page.getByLabel('Current milestone',{exact:true}).fill('Portfolio Lab QA verified');await page.getByRole('button',{name:'Save project',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Project saved.'})).toBeVisible();
    await page.getByText('Add manual memory',{exact:true}).click();await page.getByRole('combobox',{name:'Type',exact:true}).selectOption('architecture');await page.getByLabel('Title',{exact:true}).fill('Market data architecture');await page.getByLabel('Memory content',{exact:true}).fill('MarketDataService is server-only. Historical chart uses split-adjusted close.');await page.getByRole('button',{name:'Save manual memory',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Memory saved and indexed.'})).toBeVisible();await expect(page.getByText('Source: manual',{exact:false})).toBeVisible();
    await page.getByLabel('Semantic search',{exact:true}).fill('market data architecture');await page.getByRole('button',{name:'Search project memory',exact:true}).click();await expect(page.getByRole('heading',{name:'Search results · 1',exact:true})).toBeVisible();await expect(page.getByText(/similarity .*relevance/)).toBeVisible();
    await page.evaluate(() => window.scrollTo(0,0));await page.screenshot({path:resolve('docs/project-memory-v1/project-memory-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});const overflow=await page.evaluate(() => [...document.querySelectorAll('h1,fieldset,input,textarea,select,.detail-fields,.memory-entry,.button')].filter(e => e.getBoundingClientRect().right>innerWidth+1).map(e => ({tag:e.tagName,class:e.className,width:e.getBoundingClientRect().width})));expect(overflow).toEqual([]);expect(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(() => window.scrollTo(0,0));await page.screenshot({path:resolve('docs/project-memory-v1/project-memory-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});
    await page.getByRole('button',{name:'Sync completed task outcomes',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Scanned 0 · created 0 · already existed 0 · embedding failures 0'})).toBeVisible();
    await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Overview',exact:true}).click();await page.getByLabel('Project',{exact:true}).selectOption(projectId);expect(await page.getByLabel('Repository context').locator('option').count()).toBe(2);await expect(page.locator('.repository-context-path')).toHaveText(path);await page.getByLabel('What should Jonas OS do?').fill('Continue market data architecture');await page.getByRole('button',{name:'Delegate',exact:true}).click();await expect(page.getByText('QA only: goal accepted; no coding task was created.',{exact:true})).toBeVisible();await page.evaluate(() => window.scrollTo(0,0));await page.screenshot({path:resolve('docs/project-memory-v1/project-delegation.png'),fullPage:true});
    await page.getByLabel('Project',{exact:true}).selectOption('');await page.getByLabel('Repository context').selectOption({label:`${repositoryName} · ${path.length>50 ? `…${path.slice(-49)}` : path}`});await page.getByLabel('What should Jonas OS do?').fill('Repository-only QA goal');await page.getByRole('button',{name:'Delegate',exact:true}).click();await expect(page.getByText('QA only: goal accepted; no coding task was created.',{exact:true})).toBeVisible();
    const hostile=await request.post(`/api/projects/${projectId}/memories`,{headers:{Origin:'https://evil.example','X-Request-ID':randomUUID()},data:{kind:'fact',content:'Never persist'}});expect(hostile.status()).toBe(403);
    await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Projects',exact:true}).click();await page.getByRole('link',{name:projectName,exact:true}).click();await page.getByRole('button',{name:'Archive manual memory',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Manual memory archived.'})).toBeVisible();await expect(page.getByRole('button',{name:'Archive manual memory',exact:true})).toHaveCount(0);
    expect((await pool.query('select count(*)::int as count from tasks')).rows[0].count).toBe(before);expect(errors).toEqual([]);
  } finally {
    const rows=await pool.query('select id from projects where name=$1',[projectName]);for(const row of rows.rows)await pool.query('delete from projects where id=$1',[row.id]);
    if(registryId)await pool.query('delete from repositories where id=$1',[registryId]);await pool.end();await rm(directory,{recursive:true,force:true});
  }
});
