import { expect, test } from '@playwright/test';
import { resolve } from 'node:path';
const taskId = '10000000-0000-4000-8000-000000000003';
const decisionId = '10000000-0000-4000-8000-000000000501';
const screenshot = (name: string) => resolve('docs/control-plane', name);
test('operator workflow, local security and visual layouts', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Overview', exact: true })).toBeVisible();
  await expect(page.getByText('DEVELOPMENT FIXTURES', { exact: false })).toBeVisible();
  await expect(page.getByText('Checking system')).not.toBeVisible();
  await page.screenshot({ path: screenshot('overview-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.screenshot({ path: screenshot('overview-laptop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: screenshot('overview-mobile.png'), fullPage: true });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: screenshot('overview-dark.png'), fullPage: true });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto('/tasks');
  await expect(page.getByRole('table')).toBeVisible();
  await page.getByLabel('Search tasks').fill('dividend');
  await page.getByRole('button', { name: 'Apply' }).click();
  await expect(page.getByRole('link', { name: 'Correct dividend currency conversion' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Export analytics as a CSV file' })).not.toBeVisible();
  await page.getByRole('link', { name: 'Correct dividend currency conversion' }).click();
  await expect(page.getByRole('heading', { name: 'Lifecycle' })).toBeVisible();
  await expect(page.getByText('Deterministic verification', { exact: true })).toHaveCount(2);
  await expect(page.getByText('APPROVE', { exact: true })).toBeVisible();
  await page.screenshot({ path: screenshot('task-detail-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 1024, height: 768 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: screenshot('task-detail-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/decisions');
  await expect(page.getByRole('heading', { name: 'Decisions', exact: true })).toBeVisible();
  await page.screenshot({ path: screenshot('decisions-desktop.png'), fullPage: true });
  await page.goto(`/decisions/${decisionId}`);
  await expect(page.getByLabel('Your answer')).toBeVisible();
  await page.getByRole('button', { name: 'Abandon task', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Confirm abandonment' })).toBeVisible();
  await page.getByRole('button', { name: 'Keep task' }).click();
  await page.getByLabel('Your answer').fill('Require a verified second factor and preserve all existing identity checks.');
  await page.route('**/api/commands/answer', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Enqueue failed. The decision remains open.' }) }));
  await page.getByRole('button', { name: 'Save answer & resume' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Enqueue failed' })).toBeVisible();
  await expect(page.getByLabel('Your answer')).toBeVisible();
  await page.unroute('**/api/commands/answer');
  await page.getByRole('button', { name: 'Save answer & resume' }).click();
  await expect(page.getByText('Answer saved. Task queued.')).toBeVisible();
  await page.goto('/tasks/10000000-0000-4000-8000-000000000004');
  await expect(page.getByRole('heading', { name: 'Choose the account recovery policy' })).toBeVisible();
  await expect(page.getByText('The recovery branch can bypass the second factor.')).toBeVisible();
  await page.goto('/agents');
  await expect(page.getByRole('heading', { name: 'Local Chief' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Strong coding' })).toBeVisible();
  await page.screenshot({ path: screenshot('agents-desktop.png'), fullPage: true });
  await page.goto('/projects');
  await expect(page.getByRole('table')).toBeVisible();
  await page.getByRole('link', { name: 'investi', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'investi', exact: true })).toBeVisible();
  await page.goto('/activity');
  await expect(page.getByRole('heading', { name: 'Activity', exact: true })).toBeVisible();
  await page.goto('/');
  await page.getByLabel('What should Jonas OS do?').fill('Build a bounded fixture export');
  await page.getByLabel('Repository context').selectOption({ label: 'investi' });
  await page.getByRole('button', { name: 'Delegate', exact: true }).click();
  await expect(page.getByText('Task queued · Build a bounded fixture export')).toBeVisible();
  await page.getByRole('link', { name: 'Inspect task', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Build a bounded fixture export' })).toBeVisible();
  await page.goto('/');
  await page.getByLabel('What should Jonas OS do?').fill('Clarify this fixture');
  await page.getByRole('button', { name: 'Delegate', exact: true }).click();
  await expect(page.getByText('Chief needs clarification')).toBeVisible();
  await page.getByLabel('What should Jonas OS do?').fill('No action required');
  await page.getByRole('button', { name: 'Delegate', exact: true }).click();
  await expect(page.getByText('No action needed')).toBeVisible();
  const hostile = await request.post('/api/commands/delegate', { headers: { Origin: 'https://evil.example', 'X-Request-ID': '10000000-0000-4000-8000-000000009999' }, data: { goal: 'Never execute' } });
  expect(hostile.status()).toBe(403);
  const rebinding = await request.get('/', { headers: { Host: 'evil.example:3107' } });
  expect(rebinding.status()).toBe(403);
  await page.goto(`/tasks/${taskId}`);
  expect(errors).toEqual([]);
});
